### ISSUE TITLE
[RFE] : allowing a .cfg file to preseed default settings like url

### ISSUE THREAD

**Issue by arrfab** [fedora-infra/fasjson-client#12]
Per discussion with @abompard here is a RFE suggestion : having a kind of .cfg file that can be parsed (but optional) by fasjson-client in HOME directory (path to be discussed) to point automatically fasjson-client to a specific url instead of having to specify on each cli call with a parameter.
That would permit to configure automatically different environments (like dev/staging/prod) through that file (and configuration management eventuallly if needed) and so different fasjson URL.
If nothing found and nothing specified through cli parameter, it can just then use the default values

Ideas ? opinions ?

**Comment by abompard** [comment]
**Acceptance Criteria**

- The client is capable of parsing files in a standard format (TOML preferred)
- 3 files are parsed in order or precedence if they exist:
  1. one in `/etc/fasjson-client/config.toml`
  2. one in `~/.config/fasjson-client/config.toml`
  3. one in the current working directory `./config.toml`
- settings in the former get overwritten by settings in the latter
- the script accepts a command-line switch to select a config file. If given, it is the only config file loaded
- the `url` parameter can be configured in the configuration
- the arguments specific to the `get-cert` subcommand are read from a `[cli.get-cert]` section in the configuration file.
- command-line switches override the configuration files values
- an appropriate error is displayed if any of the configuration files' syntax is wrong

**Definition of Done**

- All the above completed
- 100% unit test coverage
- Documentation is written in the `docs` directory
- Code passes the bandit security analyser
- Dependencies are checked for compatible licenses
- Code is formatted according to the Black tool
