### ISSUE TITLE
bravado open-api spec 3.0

### ISSUE THREAD

**Issue by odra** [fedora-infra/fasjson-client#3]
As a developer, I want to be able to use an open-api spec 3.0 format as the spec source for my fasjson client.

We are using bravado, an open-api spec library for python, that does not support the latest open-api spec format.

I think we could:

* contribute to bravado enabling it support
* fork it and enable
* create our own solution

I would prefer to contribute to bravado which is an existing tooling already used by the python community.

**Comment by abompard** [comment]
I second that, contributing to our upstream projects when possible is important.
